// Auto-generated from JSON schemas
// Do not edit this file directly

// Album
export interface Album {
  id?: number;
  title?: string;
  artist?: string;
  genre?: string;
  release_date?: string;
  label?: string;
  tracks?: number;
  /** Duration in seconds */
  duration?: number;
  rating?: number;
  price?: number;
  currency?: string;
  cover?: string;
}

// Article
export interface Article {
  id?: number;
  title?: string;
  slug?: string;
  author?: string;
  author_id?: number;
  content?: string;
  excerpt?: string;
  category?: string;
  tags?: Array;
  status?: string;
  views?: number;
  likes?: number;
  comments_count?: number;
  featured_image?: string;
  published_at?: string;
  updated_at?: string;
}

// Book
export interface Book {
  id?: number;
  title?: string;
  author?: string;
  isbn?: string;
  description?: string;
  genre?: string;
  publisher?: string;
  published_date?: string;
  pages?: number;
  language?: string;
  price?: number;
  currency?: string;
  rating?: number;
  cover?: string;
}

// Car
export interface Car {
  id?: number;
  make?: string;
  model?: string;
  year?: number;
  color?: string;
  vin?: string;
  type?: string;
  fuel_type?: string;
  transmission?: string;
  mileage?: number;
  price?: number;
  currency?: string;
  condition?: string;
  features?: Array;
  image?: string;
}

// Category
export interface Category {
  id?: number;
  name?: string;
  slug?: string;
  description?: string;
  parent_id?: number;
  order?: number;
  icon?: string;
  color?: string;
  items_count?: number;
  created_at?: string;
}

// City
export interface City {
  /** City ID */
  id: number;
  /** City name */
  name: string;
  /** Country name */
  country: string;
  /** Country ISO code */
  country_code?: string;
  /** State or province */
  state?: string;
  /** Latitude */
  latitude?: number;
  /** Longitude */
  longitude?: number;
  /** Population */
  population?: number;
  /** Timezone */
  timezone?: string;
  /** Elevation in meters */
  elevation?: number;
}

// Comment
export interface Comment {
  /** Unique identifier */
  id: number;
  /** Associated post ID */
  post_id: number;
  /** Comment author ID */
  user_id: number;
  /** Comment text */
  body: string;
  /** Creation timestamp */
  created_at?: string;
  /** Number of likes */
  likes?: number;
}

// Company
export interface Company {
  id?: number;
  name?: string;
  slogan?: string;
  description?: string;
  industry?: string;
  size?: string;
  founded_year?: number;
  headquarters?: string;
  country?: string;
  website?: string;
  email?: string;
  phone?: string;
  revenue?: number;
  employees?: number;
  logo?: string;
}

// Contact
export interface Contact {
  id?: number;
  first_name?: string;
  last_name?: string;
  email?: string;
  phone?: string;
  company?: string;
  job_title?: string;
  address?: string;
  city?: string;
  country?: string;
  notes?: string;
  tags?: Array;
  created_at?: string;
}

// Country
export interface Country {
  /** Country ID */
  id: number;
  /** Country name */
  name: string;
  /** ISO 3166-1 alpha-2 code */
  code: string;
  /** ISO 3166-1 alpha-3 code */
  code3?: string;
  /** Capital city */
  capital?: string;
  /** Geographic region */
  region?: string;
  /** Geographic subregion */
  subregion?: string;
  /** Population */
  population?: number;
  /** Area in km² */
  area?: number;
  /** Official languages */
  languages?: Array;
  /** Currency code */
  currency?: string;
  /** Phone calling code */
  calling_code?: string;
  /** Primary timezone */
  timezone?: string;
  /** Flag image URL */
  flag?: string;
}

// Coupon
export interface Coupon {
  id?: number;
  code?: string;
  description?: string;
  discount_type?: string;
  discount_value?: number;
  min_purchase?: number;
  max_discount?: number;
  currency?: string;
  usage_limit?: number;
  used_count?: number;
  valid_from?: string;
  valid_until?: string;
  active?: boolean;
}

// Course
export interface Course {
  id?: number;
  title?: string;
  description?: string;
  instructor?: string;
  category?: string;
  level?: string;
  /** Duration in hours */
  duration?: number;
  lessons?: number;
  enrolled?: number;
  rating?: number;
  price?: number;
  currency?: string;
  language?: string;
  certificate?: boolean;
  thumbnail?: string;
  created_at?: string;
}

// Crypto
export interface Crypto {
  id?: number;
  symbol?: string;
  name?: string;
  price?: number;
  change_24h?: number;
  volume_24h?: number;
  market_cap?: number;
  circulating_supply?: number;
  total_supply?: number;
  high_24h?: number;
  low_24h?: number;
  /** All-time high */
  ath?: number;
  ath_date?: string;
  rank?: number;
  timestamp?: string;
}

// Currency
export interface Currency {
  /** Currency ID */
  id: number;
  /** ISO 4217 currency code */
  code: string;
  /** Currency name */
  name: string;
  /** Currency symbol */
  symbol?: string;
  /** Exchange rate to USD */
  exchange_rate?: number;
  /** Countries using this currency */
  countries?: Array;
  /** Last update time */
  updated_at?: string;
}

// Event
export interface Event {
  id?: number;
  title?: string;
  description?: string;
  category?: string;
  start_date?: string;
  end_date?: string;
  location?: string;
  city?: string;
  country?: string;
  venue?: string;
  organizer?: string;
  capacity?: number;
  price?: number;
  currency?: string;
  is_online?: boolean;
  url?: string;
}

// FAQ
export interface FAQ {
  id?: number;
  question?: string;
  answer?: string;
  category?: string;
  order?: number;
  helpful_count?: number;
  views?: number;
  created_at?: string;
  updated_at?: string;
}

// Flight
export interface Flight {
  id?: number;
  flight_number?: string;
  airline?: string;
  origin?: string;
  origin_code?: string;
  destination?: string;
  destination_code?: string;
  departure_time?: string;
  arrival_time?: string;
  /** Duration in minutes */
  duration?: number;
  aircraft?: string;
  price?: number;
  currency?: string;
  available_seats?: number;
  class?: string;
  status?: string;
}

// Hotel
export interface Hotel {
  id?: number;
  name?: string;
  description?: string;
  stars?: number;
  address?: string;
  city?: string;
  country?: string;
  latitude?: number;
  longitude?: number;
  phone?: string;
  email?: string;
  website?: string;
  rating?: number;
  price_per_night?: number;
  currency?: string;
  rooms?: number;
  amenities?: Array;
  image?: string;
}

// Image
export interface Image {
  id?: number;
  title?: string;
  description?: string;
  url?: string;
  thumbnail_url?: string;
  width?: number;
  height?: number;
  /** Size in bytes */
  size?: number;
  format?: string;
  tags?: Array;
  photographer?: string;
  location?: string;
  uploaded_at?: string;
}

// Invoice
export interface Invoice {
  id?: number;
  invoice_number?: string;
  customer_id?: number;
  customer_name?: string;
  customer_email?: string;
  amount?: number;
  tax?: number;
  total?: number;
  currency?: string;
  status?: string;
  issue_date?: string;
  due_date?: string;
  paid_at?: string;
}

// Job
export interface Job {
  id?: number;
  title?: string;
  company?: string;
  description?: string;
  requirements?: string;
  location?: string;
  country?: string;
  type?: string;
  level?: string;
  salary_min?: number;
  salary_max?: number;
  currency?: string;
  remote?: boolean;
  posted_at?: string;
  expires_at?: string;
}

// Language
export interface Language {
  /** Language ID */
  id: number;
  /** Language name */
  name: string;
  /** Native language name */
  native_name?: string;
  /** ISO 639-1 code */
  code: string;
  /** ISO 639-2 code */
  code3?: string;
  /** Language family */
  family?: string;
  /** Number of speakers */
  speakers?: number;
  /** Countries where spoken */
  countries?: Array;
}

// Match
export interface Match {
  id?: number;
  home_team?: string;
  away_team?: string;
  home_score?: number;
  away_score?: number;
  sport?: string;
  league?: string;
  stadium?: string;
  city?: string;
  status?: string;
  match_date?: string;
  attendance?: number;
}

// Meeting
export interface Meeting {
  id?: number;
  title?: string;
  description?: string;
  organizer?: string;
  start_time?: string;
  end_time?: string;
  location?: string;
  type?: string;
  attendees_count?: number;
  status?: string;
  online_link?: string;
  created_at?: string;
}

// Message
export interface Message {
  id?: number;
  conversation_id?: number;
  sender_id?: number;
  sender_name?: string;
  receiver_id?: number;
  receiver_name?: string;
  content?: string;
  type?: string;
  read?: boolean;
  created_at?: string;
  read_at?: string;
}

// Movie
export interface Movie {
  id?: number;
  title?: string;
  description?: string;
  director?: string;
  genre?: string;
  year?: number;
  /** Duration in minutes */
  duration?: number;
  rating?: number;
  language?: string;
  country?: string;
  budget?: number;
  revenue?: number;
  poster?: string;
  released_at?: string;
}

// News
export interface News {
  id?: number;
  headline?: string;
  summary?: string;
  content?: string;
  author?: string;
  source?: string;
  category?: string;
  country?: string;
  language?: string;
  tags?: Array;
  image?: string;
  url?: string;
  published_at?: string;
}

// Note
export interface Note {
  id?: number;
  title?: string;
  content?: string;
  author_id?: number;
  author?: string;
  color?: string;
  tags?: Array;
  pinned?: boolean;
  archived?: boolean;
  created_at?: string;
  updated_at?: string;
}

// Notification
export interface Notification {
  id?: number;
  user_id?: number;
  title?: string;
  message?: string;
  type?: string;
  priority?: string;
  read?: boolean;
  action_url?: string;
  created_at?: string;
  read_at?: string;
}

// Order
export interface Order {
  id?: number;
  order_number?: string;
  customer_id?: number;
  customer_name?: string;
  customer_email?: string;
  items_count?: number;
  subtotal?: number;
  tax?: number;
  shipping?: number;
  total?: number;
  currency?: string;
  status?: string;
  payment_method?: string;
  shipping_address?: string;
  created_at?: string;
  updated_at?: string;
}

// Organization
export interface Organization {
  id?: number;
  name?: string;
  type?: string;
  description?: string;
  website?: string;
  email?: string;
  phone?: string;
  address?: string;
  city?: string;
  country?: string;
  employees?: number;
  founded?: number;
  logo?: string;
}

// Payment
export interface Payment {
  id?: number;
  transaction_id?: string;
  order_id?: number;
  customer_id?: number;
  amount?: number;
  currency?: string;
  method?: string;
  status?: string;
  card_last4?: string;
  card_brand?: string;
  created_at?: string;
  processed_at?: string;
}

// Player
export interface Player {
  id?: number;
  name?: string;
  jersey_number?: number;
  position?: string;
  team_id?: number;
  team_name?: string;
  age?: number;
  /** Height in cm */
  height?: number;
  /** Weight in kg */
  weight?: number;
  nationality?: string;
  goals?: number;
  assists?: number;
  photo?: string;
}

// Podcast
export interface Podcast {
  id?: number;
  title?: string;
  description?: string;
  host?: string;
  category?: string;
  episode_number?: number;
  season?: number;
  /** Duration in minutes */
  duration?: number;
  release_date?: string;
  plays?: number;
  rating?: number;
  language?: string;
  audio_url?: string;
  cover?: string;
}

// Post
export interface Post {
  id?: number;
  user_id?: number;
  title?: string;
  body?: string;
  published?: boolean;
  created_at?: string;
  views?: number;
  likes?: number;
}

// Product
export interface Product {
  /** Unique identifier */
  id: number;
  /** Product name */
  name: string;
  /** Product description */
  description?: string;
  /** Product price */
  price: number;
  /** Price currency */
  currency?: string;
  /** Product category */
  category?: string;
  /** Brand name */
  brand?: string;
  /** Stock keeping unit */
  sku?: string;
  /** Available quantity */
  stock?: number;
  /** Product image URL */
  image?: string;
}

// Project
export interface Project {
  id?: number;
  name?: string;
  description?: string;
  owner?: string;
  owner_id?: number;
  status?: string;
  priority?: string;
  budget?: number;
  currency?: string;
  start_date?: string;
  end_date?: string;
  /** Percentage */
  completion?: number;
  team_size?: number;
  created_at?: string;
}

// Property
export interface Property {
  id?: number;
  title?: string;
  description?: string;
  type?: string;
  status?: string;
  address?: string;
  city?: string;
  state?: string;
  country?: string;
  zip_code?: string;
  latitude?: number;
  longitude?: number;
  price?: number;
  currency?: string;
  bedrooms?: number;
  bathrooms?: number;
  /** Square meters */
  area?: number;
  year_built?: number;
  features?: Array;
  image?: string;
}

// Quote
export interface Quote {
  id?: number;
  text?: string;
  author?: string;
  category?: string;
  tags?: Array;
  language?: string;
  likes?: number;
  created_at?: string;
}

// Recipe
export interface Recipe {
  id?: number;
  title?: string;
  description?: string;
  cuisine?: string;
  category?: string;
  difficulty?: string;
  /** Minutes */
  prep_time?: number;
  /** Minutes */
  cook_time?: number;
  servings?: number;
  calories?: number;
  rating?: number;
  author?: string;
  image?: string;
  created_at?: string;
}

// Restaurant
export interface Restaurant {
  id?: number;
  name?: string;
  description?: string;
  cuisine?: string;
  address?: string;
  city?: string;
  country?: string;
  latitude?: number;
  longitude?: number;
  phone?: string;
  email?: string;
  website?: string;
  rating?: number;
  price_range?: string;
  opening_hours?: string;
  delivery?: boolean;
  image?: string;
}

// Review
export interface Review {
  /** Review ID */
  id: number;
  /** Product ID */
  product_id: number;
  /** Reviewer user ID */
  user_id: number;
  /** Rating (1-5 stars) */
  rating: number;
  /** Review title */
  title?: string;
  /** Review content */
  body?: string;
  /** Verified buyer */
  verified_purchase?: boolean;
  /** Helpful votes */
  helpful_count?: number;
  /** Review date */
  created_at?: string;
}

// Stock
export interface Stock {
  id?: number;
  symbol?: string;
  name?: string;
  exchange?: string;
  price?: number;
  change?: number;
  change_percent?: number;
  volume?: number;
  market_cap?: number;
  high?: number;
  low?: number;
  open?: number;
  previous_close?: number;
  currency?: string;
  timestamp?: string;
}

// Student
export interface Student {
  id?: number;
  student_id?: string;
  first_name?: string;
  last_name?: string;
  email?: string;
  phone?: string;
  date_of_birth?: string;
  gender?: string;
  grade?: string;
  major?: string;
  gpa?: number;
  address?: string;
  city?: string;
  country?: string;
  enrolled_date?: string;
  avatar?: string;
}

// Subscription
export interface Subscription {
  id?: number;
  user_id?: number;
  plan?: string;
  status?: string;
  price?: number;
  currency?: string;
  billing_cycle?: string;
  start_date?: string;
  end_date?: string;
  next_billing_date?: string;
  auto_renew?: boolean;
  trial_ends_at?: string;
}

// Tag
export interface Tag {
  id?: number;
  name?: string;
  slug?: string;
  description?: string;
  color?: string;
  usage_count?: number;
  created_at?: string;
}

// Task
export interface Task {
  id?: number;
  project_id?: number;
  title?: string;
  description?: string;
  assignee?: string;
  assignee_id?: number;
  status?: string;
  priority?: string;
  due_date?: string;
  estimated_hours?: number;
  actual_hours?: number;
  created_at?: string;
  completed_at?: string;
}

// Team
export interface Team {
  id?: number;
  name?: string;
  sport?: string;
  league?: string;
  founded?: number;
  city?: string;
  country?: string;
  stadium?: string;
  coach?: string;
  wins?: number;
  losses?: number;
  draws?: number;
  logo?: string;
}

// Testimonial
export interface Testimonial {
  id?: number;
  name?: string;
  position?: string;
  company?: string;
  message?: string;
  rating?: number;
  avatar?: string;
  featured?: boolean;
  created_at?: string;
}

// Ticket
export interface Ticket {
  id?: number;
  ticket_number?: string;
  subject?: string;
  description?: string;
  customer_id?: number;
  customer_name?: string;
  customer_email?: string;
  assigned_to?: string;
  priority?: string;
  status?: string;
  category?: string;
  created_at?: string;
  updated_at?: string;
  resolved_at?: string;
}

// Todo
export interface Todo {
  /** Unique identifier */
  id: number;
  /** Owner user ID */
  user_id?: number;
  /** Todo title */
  title: string;
  /** Completion status */
  completed: boolean;
  /** Due date */
  due_date?: string;
  /** Priority level (1-5) */
  priority?: number;
}

// User
export interface User {
  /** Unique identifier */
  id: number;
  /** Username */
  username: string;
  /** Email address */
  email: string;
  first_name?: string;
  last_name?: string;
  avatar?: string;
  gender?: 'male' | 'female';
  phone?: string;
  address?: string;
  city?: string;
  country?: string;
  created_at?: string;
}

// Video
export interface Video {
  id?: number;
  title?: string;
  description?: string;
  creator?: string;
  creator_id?: number;
  /** Duration in seconds */
  duration?: number;
  views?: number;
  likes?: number;
  dislikes?: number;
  comments_count?: number;
  category?: string;
  tags?: Array;
  thumbnail?: string;
  url?: string;
  published_at?: string;
}

// Weather
export interface Weather {
  /** Weather record ID */
  id: number;
  /** City name */
  city: string;
  /** Country name */
  country: string;
  /** Latitude */
  latitude?: number;
  /** Longitude */
  longitude?: number;
  /** Temperature in Celsius */
  temperature: number;
  /** Feels like temperature */
  feels_like?: number;
  /** Humidity percentage */
  humidity?: number;
  /** Atmospheric pressure in hPa */
  pressure?: number;
  /** Wind speed in m/s */
  wind_speed?: number;
  /** Wind direction */
  wind_direction?: string;
  /** Weather condition */
  condition?: string;
  /** Detailed description */
  description?: string;
  /** Visibility in meters */
  visibility?: number;
  /** UV index */
  uv_index?: number;
  /** Observation time */
  timestamp?: string;
}


// Resource helpers
export type ResourceName = 'albums' | 'articles' | 'books' | 'cars' | 'categories' | 'cities' | 'comments' | 'companies' | 'contacts' | 'countries' | 'coupons' | 'courses' | 'crypto' | 'currencies' | 'events' | 'faqs' | 'flights' | 'hotels' | 'images' | 'invoices' | 'jobs' | 'languages' | 'matches' | 'meetings' | 'messages' | 'movies' | 'news' | 'notes' | 'notifications' | 'orders' | 'organizations' | 'payments' | 'players' | 'podcasts' | 'posts' | 'products' | 'projects' | 'properties' | 'quotes' | 'recipes' | 'restaurants' | 'reviews' | 'stocks' | 'students' | 'subscriptions' | 'tags' | 'tasks' | 'teams' | 'testimonials' | 'tickets' | 'todos' | 'users' | 'videos' | 'weather';

export interface ResourceMap {
  albums: Album;
  articles: Article;
  books: Book;
  cars: Car;
  categories: Category;
  cities: City;
  comments: Comment;
  companies: Company;
  contacts: Contact;
  countries: Country;
  coupons: Coupon;
  courses: Course;
  crypto: Crypto;
  currencies: Currency;
  events: Event;
  faqs: FAQ;
  flights: Flight;
  hotels: Hotel;
  images: Image;
  invoices: Invoice;
  jobs: Job;
  languages: Language;
  matches: Match;
  meetings: Meeting;
  messages: Message;
  movies: Movie;
  news: News;
  notes: Note;
  notifications: Notification;
  orders: Order;
  organizations: Organization;
  payments: Payment;
  players: Player;
  podcasts: Podcast;
  posts: Post;
  products: Product;
  projects: Project;
  properties: Property;
  quotes: Quote;
  recipes: Recipe;
  restaurants: Restaurant;
  reviews: Review;
  stocks: Stock;
  students: Student;
  subscriptions: Subscription;
  tags: Tag;
  tasks: Task;
  teams: Team;
  testimonials: Testimonial;
  tickets: Ticket;
  todos: Todo;
  users: User;
  videos: Video;
  weather: Weather;
}

// API response types
export type CollectionResponse<T extends ResourceName> = ResourceMap[T][];
export type SingleResponse<T extends ResourceName> = ResourceMap[T];
