#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// Directories
const schemasDir = path.join(__dirname, '..', 'schemas');
const typesOutputFile = path.join(__dirname, '..', '..', 'frontend', 'types', 'api.ts');
const manifestOutputFile = path.join(__dirname, '..', '..', 'frontend', 'lib', 'schemas-manifest.ts');
const backendSchemasDir = path.join(__dirname, '..', '..', 'backend', 'internal', 'schema', 'embedded');

// Ensure output directories exist
const typesDir = path.dirname(typesOutputFile);
if (!fs.existsSync(typesDir)) {
  fs.mkdirSync(typesDir, { recursive: true });
}
if (!fs.existsSync(backendSchemasDir)) {
  fs.mkdirSync(backendSchemasDir, { recursive: true });
}

// Get all JSON schema files
function getJsonFiles(dir) {
  const files = [];
  const items = fs.readdirSync(dir);

  for (const item of items) {
    const fullPath = path.join(dir, item);
    const stat = fs.statSync(fullPath);

    if (stat.isDirectory()) {
      files.push(...getJsonFiles(fullPath));
    } else if (item.endsWith('.json')) {
      files.push(fullPath);
    }
  }

  return files;
}

const schemaFiles = getJsonFiles(schemasDir);
const schemas = [];

// Read and parse all schemas
for (const file of schemaFiles) {
  const content = fs.readFileSync(file, 'utf8');
  const schema = JSON.parse(content);
  const resourceName = path.basename(file, '.json');
  const group = path.basename(path.dirname(file));
  schemas.push({ name: resourceName, schema, group });
}

// Generate TypeScript types
function generateTypeFromSchema(schema) {
  const properties = schema.properties || {};
  const required = schema.required || [];

  const fields = Object.entries(properties).map(([key, prop]) => {
    const isRequired = required.includes(key);
    const optional = isRequired ? '' : '?';

    let type = 'any';
    if (prop.type === 'string') type = 'string';
    else if (prop.type === 'number' || prop.type === 'integer') type = 'number';
    else if (prop.type === 'boolean') type = 'boolean';
    else if (prop.type === 'array') type = 'any[]';
    else if (prop.type === 'object') type = 'Record<string, any>';

    return `  ${key}${optional}: ${type};`;
  });

  return fields.join('\n');
}

// Generate TypeScript file content
let tsContent = `// Auto-generated TypeScript types from JSON schemas
// DO NOT EDIT - This file is automatically generated

`;

for (const { name, schema } of schemas) {
  const typeName = name.charAt(0).toUpperCase() + name.slice(1);
  const typeContent = generateTypeFromSchema(schema);

  tsContent += `export interface ${typeName} {\n${typeContent}\n}\n\n`;
}

// Write TypeScript types
fs.writeFileSync(typesOutputFile, tsContent, 'utf8');

// Copy schema files to backend
let copiedCount = 0;
for (const file of schemaFiles) {
  const filename = path.basename(file);
  const targetPath = path.join(backendSchemasDir, filename);
  fs.copyFileSync(file, targetPath);
  copiedCount++;
}

// Generate schemas manifest for frontend (avoids fs usage in Cloudflare Workers)
const manifestEntries = schemas
  .sort((a, b) => a.name.localeCompare(b.name))
  .map(({ name, schema, group }) => `  { name: ${JSON.stringify(name)}, group: ${JSON.stringify(group)}, schema: ${JSON.stringify(schema)} }`)
  .join(',\n');

const manifestContent = `// Auto-generated schemas manifest - DO NOT EDIT
// Run: pnpm --filter @api-mockly/shared generate-types

export interface SchemaEntry {
  name: string;
  group: string;
  schema: Record<string, any>;
}

export const schemasManifest: SchemaEntry[] = [
${manifestEntries},
];
`;

fs.writeFileSync(manifestOutputFile, manifestContent, 'utf8');

// Output summary
const schemaNames = schemas.map(s => s.name.charAt(0).toUpperCase() + s.name.slice(1)).join(', ');
console.log(`✓ Generated TypeScript types for ${schemas.length} schemas`);
console.log(`  Output: ${typesOutputFile}`);
console.log(`✓ Generated schemas manifest at ${manifestOutputFile}`);
console.log(`  Schemas: ${schemaNames}`);
console.log(`✓ Copied ${copiedCount} schema files to backend/internal/schema/embedded/`);
